### ISSUE TITLE
The Git version tag does not appear on the web

### ISSUE THREAD

**Issue by viyamKUN** [doppiolab/mcman#2]
<img width="434" alt="스크린샷 2022-08-03 오후 11 33 57" src="https://user-images.githubusercontent.com/54323618/182635193-bbb3b82b-b94b-4959-8914-a700d11a043b.png">

**Comment by jeongukjae** [comment]
Fixed by

- https://github.com/doppiolab/mcman/commit/8e1a9efdfa01124bd3daf2f81f7595d6cf801f08
- https://github.com/doppiolab/mcman/commit/b2179eaf738ed32d61eb94bfbc3d407ac5b63f31
